using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using VidlyMVCApp.DL;
using VidlyMVCApp.Models;

namespace VidlyMVCApp.BL
{
    public class VidlyBL
    {
        private VidlyDLContext _dlContext;

        public VidlyBL(VidlyDLContext dlContext)
        {
            _dlContext = dlContext;
        }

        // guess this should be done in DL??
        internal List<Movie> GetMovies()
        {
            return _dlContext.Movies.ToList();
        }

        /// <summary>
        /// Save a movie to database, de id is autogenerated
        /// </summary>
        /// <param name="movie"></param>
        internal void SaveMovie(Movie movie)
        {
            _dlContext.Movies.Add(movie);
            _dlContext.SaveChanges();
        }
    }
}